# Site settings
name: 刘挚珂 - 积累与分享
email: liuzhike.sam@gmail.com
author: LiuZhiKe
url: http://www.liuzhike.com
resume_site: http://www.liuzhike.com
github: https://github.com/liuzhike/
baseurl: ""
description: 开始并完成一件事, 比做好它更重要. 因为只要开始了, 你就有机会把它做得更好.
meta_description: 刘挚珂;个人博客;三人行，必有我师焉；择其善者而从之，其不善者而改之.
motto: just do it
banner: 三人行，必有我师焉；择其善者而从之，其不善者而改之.

#permalink: /:categories/:year/:month/:day/:title/

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

github_username: liuzhike
highlighter: rouge

# Build settings
markdown: kramdown

FB:
  comments :
    provider : duoshuo
    duoshuo:
        short_name : luoyan35714
    disqus :
        short_name : freudkang
    # facebook :
    #   appid : 123
    #   num_posts: 5
    #   width: 580
    #   colorscheme: light